spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://cinema-db:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: none
    show-sql: false